name: Release Tree Weaver

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: '25.3'
        rebar3-version: '3.22.1'

    - name: Build Release
      run: |
        rebar3 compile
        rebar3 escriptize

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          _build/default/bin/tree-weaver
